// Code generated by "stringer -type=Country"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Japan-1]
	_ = x[China-2]
	_ = x[Korea-3]
}

const _Country_name = "JapanChinaKorea"

var _Country_index = [...]uint8{0, 5, 10, 15}

func (i Country) String() string {
	i -= 1
	if i < 0 || i >= Country(len(_Country_index)-1) {
		return "Country(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Country_name[_Country_index[i]:_Country_index[i+1]]
}
